/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeRouteImport } from './routes/_authenticated/te'
import { Route as AuthenticatedRecompensasRouteImport } from './routes/_authenticated/recompensas'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated/progreso'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedGenerandoRouteImport } from './routes/_authenticated/generando'
import { Route as AuthenticatedEjerciciosRouteImport } from './routes/_authenticated/ejercicios'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedAnalizarRouteImport } from './routes/_authenticated/analizar'
import { Route as AuthenticatedActivateRouteImport } from './routes/_authenticated/activate'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeRoute = AuthenticatedTeRouteImport.update({
  id: '/te',
  path: '/te',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecompensasRoute =
  AuthenticatedRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerandoRoute = AuthenticatedGenerandoRouteImport.update({
  id: '/generando',
  path: '/generando',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEjerciciosRoute = AuthenticatedEjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalizarRoute = AuthenticatedAnalizarRouteImport.update({
  id: '/analizar',
  path: '/analizar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivateRoute = AuthenticatedActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/analizar': typeof AuthenticatedAnalizarRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/ejercicios': typeof AuthenticatedEjerciciosRoute
  '/generando': typeof AuthenticatedGenerandoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/te': typeof AuthenticatedTeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/analizar': typeof AuthenticatedAnalizarRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/ejercicios': typeof AuthenticatedEjerciciosRoute
  '/generando': typeof AuthenticatedGenerandoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/te': typeof AuthenticatedTeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activate': typeof AuthenticatedActivateRoute
  '/_authenticated/analizar': typeof AuthenticatedAnalizarRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/ejercicios': typeof AuthenticatedEjerciciosRoute
  '/_authenticated/generando': typeof AuthenticatedGenerandoRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/_authenticated/recompensas': typeof AuthenticatedRecompensasRoute
  '/_authenticated/te': typeof AuthenticatedTeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activate'
    | '/analizar'
    | '/compras'
    | '/ejercicios'
    | '/generando'
    | '/onboarding'
    | '/perfil'
    | '/plan'
    | '/premium'
    | '/progreso'
    | '/recompensas'
    | '/te'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activate'
    | '/analizar'
    | '/compras'
    | '/ejercicios'
    | '/generando'
    | '/onboarding'
    | '/perfil'
    | '/plan'
    | '/premium'
    | '/progreso'
    | '/recompensas'
    | '/te'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activate'
    | '/_authenticated/analizar'
    | '/_authenticated/compras'
    | '/_authenticated/ejercicios'
    | '/_authenticated/generando'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/plan'
    | '/_authenticated/premium'
    | '/_authenticated/progreso'
    | '/_authenticated/recompensas'
    | '/_authenticated/te'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/te': {
      id: '/_authenticated/te'
      path: '/te'
      fullPath: '/te'
      preLoaderRoute: typeof AuthenticatedTeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recompensas': {
      id: '/_authenticated/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof AuthenticatedRecompensasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generando': {
      id: '/_authenticated/generando'
      path: '/generando'
      fullPath: '/generando'
      preLoaderRoute: typeof AuthenticatedGenerandoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ejercicios': {
      id: '/_authenticated/ejercicios'
      path: '/ejercicios'
      fullPath: '/ejercicios'
      preLoaderRoute: typeof AuthenticatedEjerciciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analizar': {
      id: '/_authenticated/analizar'
      path: '/analizar'
      fullPath: '/analizar'
      preLoaderRoute: typeof AuthenticatedAnalizarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activate': {
      id: '/_authenticated/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthenticatedActivateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivateRoute: typeof AuthenticatedActivateRoute
  AuthenticatedAnalizarRoute: typeof AuthenticatedAnalizarRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedEjerciciosRoute: typeof AuthenticatedEjerciciosRoute
  AuthenticatedGenerandoRoute: typeof AuthenticatedGenerandoRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
  AuthenticatedRecompensasRoute: typeof AuthenticatedRecompensasRoute
  AuthenticatedTeRoute: typeof AuthenticatedTeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivateRoute: AuthenticatedActivateRoute,
  AuthenticatedAnalizarRoute: AuthenticatedAnalizarRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedEjerciciosRoute: AuthenticatedEjerciciosRoute,
  AuthenticatedGenerandoRoute: AuthenticatedGenerandoRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
  AuthenticatedRecompensasRoute: AuthenticatedRecompensasRoute,
  AuthenticatedTeRoute: AuthenticatedTeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
