/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecetasRouteImport } from './routes/recetas'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecetasIdRouteImport } from './routes/recetas.$id'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated/progreso'
import { Route as AuthenticatedProgramaRouteImport } from './routes/_authenticated/programa'
import { Route as AuthenticatedEjerciciosRouteImport } from './routes/_authenticated/ejercicios'
import { Route as AuthenticatedAlimentacionRouteImport } from './routes/_authenticated/alimentacion'
import { Route as AuthenticatedProgramaDiaRouteImport } from './routes/_authenticated/programa.$dia'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasRoute = RecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasIdRoute = RecetasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecetasRoute,
} as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramaRoute = AuthenticatedProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEjerciciosRoute = AuthenticatedEjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentacionRoute =
  AuthenticatedAlimentacionRouteImport.update({
    id: '/alimentacion',
    path: '/alimentacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramaDiaRoute =
  AuthenticatedProgramaDiaRouteImport.update({
    id: '/$dia',
    path: '/$dia',
    getParentRoute: () => AuthenticatedProgramaRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/recetas': typeof RecetasRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/alimentacion': typeof AuthenticatedAlimentacionRoute
  '/ejercicios': typeof AuthenticatedEjerciciosRoute
  '/programa': typeof AuthenticatedProgramaRouteWithChildren
  '/progreso': typeof AuthenticatedProgresoRoute
  '/recetas/$id': typeof RecetasIdRoute
  '/programa/$dia': typeof AuthenticatedProgramaDiaRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/recetas': typeof RecetasRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/alimentacion': typeof AuthenticatedAlimentacionRoute
  '/ejercicios': typeof AuthenticatedEjerciciosRoute
  '/programa': typeof AuthenticatedProgramaRouteWithChildren
  '/progreso': typeof AuthenticatedProgresoRoute
  '/recetas/$id': typeof RecetasIdRoute
  '/programa/$dia': typeof AuthenticatedProgramaDiaRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/recetas': typeof RecetasRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alimentacion': typeof AuthenticatedAlimentacionRoute
  '/_authenticated/ejercicios': typeof AuthenticatedEjerciciosRoute
  '/_authenticated/programa': typeof AuthenticatedProgramaRouteWithChildren
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/recetas/$id': typeof RecetasIdRoute
  '/_authenticated/programa/$dia': typeof AuthenticatedProgramaDiaRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/perfil'
    | '/premium'
    | '/recetas'
    | '/reset-password'
    | '/alimentacion'
    | '/ejercicios'
    | '/programa'
    | '/progreso'
    | '/recetas/$id'
    | '/programa/$dia'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/perfil'
    | '/premium'
    | '/recetas'
    | '/reset-password'
    | '/alimentacion'
    | '/ejercicios'
    | '/programa'
    | '/progreso'
    | '/recetas/$id'
    | '/programa/$dia'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/perfil'
    | '/premium'
    | '/recetas'
    | '/reset-password'
    | '/_authenticated/alimentacion'
    | '/_authenticated/ejercicios'
    | '/_authenticated/programa'
    | '/_authenticated/progreso'
    | '/recetas/$id'
    | '/_authenticated/programa/$dia'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PerfilRoute: typeof PerfilRoute
  PremiumRoute: typeof PremiumRoute
  RecetasRoute: typeof RecetasRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas': {
      id: '/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof RecetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/$id': {
      id: '/recetas/$id'
      path: '/$id'
      fullPath: '/recetas/$id'
      preLoaderRoute: typeof RecetasIdRouteImport
      parentRoute: typeof RecetasRoute
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programa': {
      id: '/_authenticated/programa'
      path: '/programa'
      fullPath: '/programa'
      preLoaderRoute: typeof AuthenticatedProgramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ejercicios': {
      id: '/_authenticated/ejercicios'
      path: '/ejercicios'
      fullPath: '/ejercicios'
      preLoaderRoute: typeof AuthenticatedEjerciciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentacion': {
      id: '/_authenticated/alimentacion'
      path: '/alimentacion'
      fullPath: '/alimentacion'
      preLoaderRoute: typeof AuthenticatedAlimentacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programa/$dia': {
      id: '/_authenticated/programa/$dia'
      path: '/$dia'
      fullPath: '/programa/$dia'
      preLoaderRoute: typeof AuthenticatedProgramaDiaRouteImport
      parentRoute: typeof AuthenticatedProgramaRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProgramaRouteChildren {
  AuthenticatedProgramaDiaRoute: typeof AuthenticatedProgramaDiaRoute
}

const AuthenticatedProgramaRouteChildren: AuthenticatedProgramaRouteChildren = {
  AuthenticatedProgramaDiaRoute: AuthenticatedProgramaDiaRoute,
}

const AuthenticatedProgramaRouteWithChildren =
  AuthenticatedProgramaRoute._addFileChildren(
    AuthenticatedProgramaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlimentacionRoute: typeof AuthenticatedAlimentacionRoute
  AuthenticatedEjerciciosRoute: typeof AuthenticatedEjerciciosRoute
  AuthenticatedProgramaRoute: typeof AuthenticatedProgramaRouteWithChildren
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlimentacionRoute: AuthenticatedAlimentacionRoute,
  AuthenticatedEjerciciosRoute: AuthenticatedEjerciciosRoute,
  AuthenticatedProgramaRoute: AuthenticatedProgramaRouteWithChildren,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RecetasRouteChildren {
  RecetasIdRoute: typeof RecetasIdRoute
}

const RecetasRouteChildren: RecetasRouteChildren = {
  RecetasIdRoute: RecetasIdRoute,
}

const RecetasRouteWithChildren =
  RecetasRoute._addFileChildren(RecetasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PerfilRoute: PerfilRoute,
  PremiumRoute: PremiumRoute,
  RecetasRoute: RecetasRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
